export type { Node, TextNode, PlaceholderNode, CaptureRefNode } from './ast.js';
export type { RenderContext, EvalMeta } from './context.js';
export type { Resolver } from './placeholders.js';
export type { Segment, EvalResult } from './evaluate.js';
export { matchesTrigger } from './matcher.js';
export { parse } from './parser.js';
export { evaluate } from './evaluate.js';
export { validateTemplate } from './validate.js';
export { generators, type Generator } from './generators.js';
export { placeholders } from './placeholders.js';
